# Generated by Django 4.1.5 on 2023-01-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now=True)),
                ('body', models.CharField(max_length=30000)),
                ('blog_image', models.ImageField(upload_to='blog-images/')),
            ],
        ),
    ]
